export enum JobTitle {
    SOFTWARE_ENGINEER = "Software Engineer",
    DATA_ANALYST = "Data Analyst",
    GRAPHIC_DESIGNER = "Graphic Designer",
    HUMAN_RESOURCES_SPECIALIST = "Human Resources Specialist",
    PROJECT_MANAGER = "Project Manager",
    MARKETING_MANAGER = "Marketing Manager",
    SALES_ASSOCIATE = "Sales Associate",
    NETWORK_ENGINEER = "Network Engineer",
    BUSINESS_ANALYST = "Business Analyst",
    PRODUCT_MANAGER = "Product Manager",
    WEB_DEVELOPER = "Web Developer",
    CYBERSECURITY_SPECIALIST = "Cybersecurity Specialist",
    FINANCIAL_ANALYST = "Financial Analyst",
    LEGAL_ADVISOR = "Legal Advisor",
    DIGITAL_MARKETING_SPECIALIST = "Digital Marketing Specialist",
    CIVIL_ENGINEER = "Civil Engineer",
    SOFTWARE_ARCHITECT = "Software Architect",
    DATA_SCIENTIST = "Data Scientist",
    USER_EXPERIENCE_DESIGNER = "User Experience Designer",
    ENVIRONMENTAL_SCIENTIST = "Environmental Scientist",
    IT_CONSULTANT = "IT Consultant",
}

